export const campanhas = [
  {
    id: 1,
    titulo: "Cestas básicas para famílias em vulnerabilidade",
    instituicao: "Instituto Esperança Viva",
    instituicaoId: 1,
    categoria: "Alimentação",
    descricao:
      "Ajude a garantir alimentação básica para 50 famílias em situação de extrema pobreza no bairro Jardim Esperança. Cada cesta alimenta uma família por 30 dias.",
    meta: 15000,
    arrecadado: 9800,
    urgente: true,
  },
  {
    id: 2,
    titulo: "Reforma da escola comunitária",
    instituicao: "ONG Raízes do Futuro",
    instituicaoId: 2,
    categoria: "Educação",
    descricao:
      "A escola atende 200 crianças e adolescentes em situação de risco. O telhado apresenta infiltrações graves que comprometem as aulas nos dias de chuva.",
    meta: 30000,
    arrecadado: 12400,
    urgente: false,
  },
  {
    id: 3,
    titulo: "Medicamentos para idosos carentes",
    instituicao: "Lar São Francisco",
    instituicaoId: 3,
    categoria: "Saúde",
    descricao:
      "O lar abriga 35 idosos em situação de abandono. Precisamos de suporte para cobrir os custos de medicamentos de uso contínuo por 6 meses.",
    meta: 8000,
    arrecadado: 7200,
    urgente: true,
  },
  {
    id: 4,
    titulo: "Kits escolares para crianças da favela",
    instituicao: "Projeto Semear",
    instituicaoId: 4,
    categoria: "Educação",
    descricao:
      "Distribuição de 300 kits escolares (mochila, cadernos, lápis e material básico) para crianças matriculadas na rede pública em comunidades carentes.",
    meta: 12000,
    arrecadado: 3500,
    urgente: false,
  },
]

export const categorias = ["Alimentação", "Educação", "Saúde", "Moradia", "Cultura"]

export const doadorMock = {
  nome: "Maria Silva",
  email: "maria@email.com",
  cpf: "123.456.789-00",
  desde: "2024-03-10",
  totalDoado: 485,
  totalDoacoes: 8,
  doacoesRecorrentes: 2,
  pontos: 665,
  ranking: 23,
  tier: "Prata",
  badges: [
    { id: 1, label: "Primeira Doação", icon: "❤️", descricao: "Fez sua primeira doação" },
    { id: 2, label: "Doador Recorrente", icon: "🔄", descricao: "Ativou uma doação recorrente" },
    { id: 3, label: "5 Doações", icon: "🏅", descricao: "Completou 5 doações" },
  ],
}

export const historicoMock = [
  {
    id: 1,
    campanhaId: 3,
    campanha: "Medicamentos para idosos carentes",
    instituicao: "Lar São Francisco",
    valor: 100,
    tipo: "recorrente",
    intervalo: "mensal",
    metodo: "cartao",
    status: "aplicado",
    data: "2025-03-01",
  },
  {
    id: 2,
    campanhaId: 1,
    campanha: "Cestas básicas para famílias em vulnerabilidade",
    instituicao: "Instituto Esperança Viva",
    valor: 50,
    tipo: "unica",
    metodo: "pix",
    status: "confirmado",
    data: "2025-02-18",
  },
  {
    id: 3,
    campanhaId: 3,
    campanha: "Medicamentos para idosos carentes",
    instituicao: "Lar São Francisco",
    valor: 100,
    tipo: "recorrente",
    intervalo: "mensal",
    metodo: "cartao",
    status: "aplicado",
    data: "2025-02-01",
  },
  {
    id: 4,
    campanhaId: 2,
    campanha: "Reforma da escola comunitária",
    instituicao: "ONG Raízes do Futuro",
    valor: 75,
    tipo: "unica",
    metodo: "pix",
    status: "aplicado",
    data: "2025-01-22",
  },
  {
    id: 5,
    campanhaId: 4,
    campanha: "Kits escolares para crianças da favela",
    instituicao: "Projeto Semear",
    valor: 60,
    tipo: "unica",
    metodo: "pix",
    status: "processado",
    data: "2025-01-10",
  },
  {
    id: 6,
    campanhaId: 1,
    campanha: "Cestas básicas para famílias em vulnerabilidade",
    instituicao: "Instituto Esperança Viva",
    valor: 100,
    tipo: "recorrente",
    intervalo: "mensal",
    metodo: "cartao",
    status: "pendente",
    data: "2025-04-01",
  },
]

export const rankingMock = [
  { posicao: 1, nome: "Carlos M.", pontos: 4820 },
  { posicao: 2, nome: "Ana B.", pontos: 3920 },
  { posicao: 3, nome: "João P.", pontos: 2750 },
]

export const necessidadesMock = [
  { id: 1, titulo: "100 cestas básicas", categoria: "Alimentação", urgente: true,  status: "aberta",   criadaEm: "2025-04-01" },
  { id: 2, titulo: "Voluntários para triagem", categoria: "Voluntariado", urgente: false, status: "aberta",   criadaEm: "2025-03-28" },
  { id: 3, titulo: "Roupas de inverno infantis", categoria: "Vestuário", urgente: false, status: "atendida", criadaEm: "2025-03-15" },
]

export const atualizacoesMock = [
  {
    id: 1,
    campanhaId: 1,
    campanha: "Cestas básicas para famílias em vulnerabilidade",
    titulo: "Meta 65% atingida!",
    mensagem: "Graças ao apoio de vocês, já arrecadamos 65% da meta. As primeiras cestas já estão sendo distribuídas para 30 famílias!",
    enviadaEm: "2025-03-20",
  },
  {
    id: 2,
    campanhaId: 1,
    campanha: "Cestas básicas para famílias em vulnerabilidade",
    titulo: "Início das entregas",
    mensagem: "Começamos as primeiras entregas. Obrigado a cada um que acreditou nessa causa!",
    enviadaEm: "2025-03-01",
  },
]

export const doacoesInstituicaoMock = [
  { id: 1, doador: "Maria S.",    valor: 100, campanhaId: 1, campanha: "Cestas básicas...", data: "2025-04-01", status: "pendente"  },
  { id: 2, doador: "Carlos M.",   valor: 200, campanhaId: 1, campanha: "Cestas básicas...", data: "2025-03-25", status: "confirmado" },
  { id: 3, doador: "Ana B.",      valor:  50, campanhaId: 1, campanha: "Cestas básicas...", data: "2025-03-20", status: "aplicado"   },
  { id: 4, doador: "João P.",     valor:  75, campanhaId: 1, campanha: "Cestas básicas...", data: "2025-03-15", status: "aplicado"   },
  { id: 5, doador: "Fernanda L.", valor: 150, campanhaId: 1, campanha: "Cestas básicas...", data: "2025-03-10", status: "aplicado"   },
]

export const instituicoesPendentesMock = [
  {
    id: 101,
    nome: "Casa do Menor Feliz",
    cnpj: "33.444.555/0001-66",
    email: "contato@casadomenorfeliz.org",
    telefone: "(21) 97777-8888",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    descricao: "Atendemos crianças e adolescentes em situação de risco social, oferecendo acolhimento, reforço escolar e atividades culturais no contra-turno.",
    documento: "cnpj_casadomenor.pdf",
    submetidaEm: "2025-04-18",
    status: "pendente",
  },
  {
    id: 102,
    nome: "Associação Mãos que Curam",
    cnpj: "77.888.999/0001-22",
    email: "maosquecuram@saude.org.br",
    telefone: "(31) 94444-5555",
    cidade: "Belo Horizonte",
    estado: "MG",
    descricao: "Prestamos assistência médica e odontológica gratuita para populações em situação de rua e comunidades sem acesso ao sistema de saúde.",
    documento: "estatuto_maosquecuram.pdf",
    submetidaEm: "2025-04-15",
    status: "pendente",
  },
  {
    id: 103,
    nome: "Instituto Arte na Periferia",
    cnpj: "44.333.222/0001-11",
    email: "arte@periferiasp.org",
    telefone: "(11) 93333-2222",
    cidade: "São Paulo",
    estado: "SP",
    descricao: "Utilizamos a arte e a cultura como ferramentas de transformação social, oferecendo aulas de música, dança, teatro e artes visuais para jovens de comunidades periféricas.",
    documento: "cnpj_arteperiferia.pdf",
    submetidaEm: "2025-04-10",
    status: "pendente",
  },
  {
    id: 104,
    nome: "Rede Solidária do Nordeste",
    cnpj: "66.777.888/0001-33",
    email: "rede@solidarianordeste.org.br",
    telefone: "(85) 98888-7777",
    cidade: "Fortaleza",
    estado: "CE",
    descricao: "Articulamos doações de alimentos, roupas e materiais de construção para famílias afetadas por secas e inundações no semiárido nordestino.",
    documento: "cnpj_redesolidaria.pdf",
    submetidaEm: "2025-04-08",
    status: "aprovada",
    resolvidaEm: "2025-04-12",
  },
  {
    id: 105,
    nome: "ONG Construindo Futuros",
    cnpj: "11.999.888/0001-77",
    email: "ong@construindofuturos.org",
    telefone: "(51) 92222-1111",
    cidade: "Porto Alegre",
    estado: "RS",
    descricao: "Oferecemos cursos profissionalizantes gratuitos para jovens em situação de vulnerabilidade, com foco em tecnologia e mercado de trabalho.",
    documento: "estatuto_construindofuturos.pdf",
    submetidaEm: "2025-04-05",
    status: "rejeitada",
    motivoRejeicao: "Documentação incompleta. O estatuto social enviado está desatualizado (anterior a 2020). Favor reenviar o documento mais recente.",
    resolvidaEm: "2025-04-09",
  },
]

export const instituicoes = [
  {
    id: 1,
    nome: "Instituto Esperança Viva",
    descricao:
      "Atuamos desde 2010 no combate à fome e à insegurança alimentar em comunidades periféricas de São Paulo. Nosso programa de cestas básicas já beneficiou mais de 5.000 famílias, e nossa cozinha comunitária serve 200 refeições por dia.",
    cidade: "São Paulo",
    estado: "SP",
    fundadoEm: 2010,
    cnpj: "12.345.678/0001-90",
    email: "contato@esperancaviva.org.br",
    telefone: "(11) 98765-4321",
    verificada: true,
    certificacoes: ["OSCIP", "Utilidade Pública Municipal", "ISO 9001"],
    balancoSocial: {
      familiasBeneficiadas: 5200,
      voluntarios: 80,
      arrecadadoTotal: 420000,
      campanhasRealizadas: 18,
    },
    redesSociais: {
      instagram: "#",
      facebook: "#",
    },
  },
  {
    id: 2,
    nome: "ONG Raízes do Futuro",
    descricao:
      "Há 8 anos transformamos espaços educacionais em zonas de risco social para que crianças e adolescentes tenham acesso a uma educação digna. Gerenciamos 3 escolas comunitárias e atendemos mais de 600 alunos por ano.",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    fundadoEm: 2016,
    cnpj: "98.765.432/0001-11",
    email: "ong@raizesdofuturo.org",
    telefone: "(21) 97654-3210",
    verificada: true,
    certificacoes: ["OSCIP", "Utilidade Pública Estadual"],
    balancoSocial: {
      familiasBeneficiadas: 1800,
      voluntarios: 55,
      arrecadadoTotal: 310000,
      campanhasRealizadas: 11,
    },
    redesSociais: {
      instagram: "#",
      facebook: "#",
    },
  },
  {
    id: 3,
    nome: "Lar São Francisco",
    descricao:
      "Cuidamos de idosos em situação de abandono e vulnerabilidade social desde 2005. Nossa casa de acolhimento oferece moradia, alimentação, assistência médica e atividades de socialização para 35 idosos em regime integral.",
    cidade: "Belo Horizonte",
    estado: "MG",
    fundadoEm: 2005,
    cnpj: "11.222.333/0001-44",
    email: "contato@larsaofrancisco.org.br",
    telefone: "(31) 96543-2100",
    verificada: true,
    certificacoes: ["OSCIP", "Utilidade Pública Municipal", "CNAS"],
    balancoSocial: {
      familiasBeneficiadas: 420,
      voluntarios: 30,
      arrecadadoTotal: 195000,
      campanhasRealizadas: 9,
    },
    redesSociais: {
      instagram: "#",
      facebook: "#",
    },
  },
  {
    id: 4,
    nome: "Projeto Semear",
    descricao:
      "Acreditamos que educação começa com as ferramentas certas. Desde 2019 distribuímos kits escolares e materiais pedagógicos para crianças em comunidades carentes, além de oferecer reforço escolar gratuito no contra-turno.",
    cidade: "Curitiba",
    estado: "PR",
    fundadoEm: 2019,
    cnpj: "55.666.777/0001-88",
    email: "ola@projetosemear.org",
    telefone: "(41) 95432-1098",
    verificada: true,
    certificacoes: ["OSCIP"],
    balancoSocial: {
      familiasBeneficiadas: 750,
      voluntarios: 40,
      arrecadadoTotal: 98000,
      campanhasRealizadas: 6,
    },
    redesSociais: {
      instagram: "#",
      facebook: "#",
    },
  },
]
