export const updatesMock = [
  {
    id: 1,
    title: "Meta 65% atingida!",
    message: "Graças ao apoio de vocês, já alcançamos 65% da nossa meta. As sessões de fisioterapia seguem acontecendo toda semana. Obrigado pelo carinho!",
    campaign: "Fisioterapia que transforma",
    sentAt: "2024-04-15",
  },
];

export const pendingInstitutionsMock = [
  {
    id: 1,
    name: "Instituto Esperança Viva",
    cnpj: "98.765.432/0001-10",
    city: "Campinas",
    state: "SP",
    email: "contato@esperancaviva.org.br",
    phone: "+55 19 3333-4444",
    description: "Organização focada em apoio a crianças em situação de vulnerabilidade social, oferecendo alimentação, educação complementar e apoio psicológico.",
    document: "estatuto_social_2024.pdf",
    status: "pendente",
    submittedAt: "2024-04-18",
  },
  {
    id: 2,
    name: "Lar Solidário Santana",
    cnpj: "11.222.333/0001-44",
    city: "Ribeirão Preto",
    state: "SP",
    email: "lar@solidariosantana.org.br",
    phone: "+55 16 3222-5555",
    description: "Abrigo para idosos em situação de abandono, com atendimento médico, fisioterapia e atividades de lazer.",
    document: "registro_cnpj_2024.pdf",
    status: "aprovada",
    submittedAt: "2024-03-10",
    resolvedAt: "2024-03-20",
  },
  {
    id: 3,
    name: "ONG Sonhos em Ação",
    cnpj: "55.666.777/0001-88",
    city: "Santos",
    state: "SP",
    email: "contato@sonhosemacao.org.br",
    phone: "+55 13 4444-6666",
    description: "Projeto de inclusão digital para jovens de comunidades carentes, oferecendo cursos de informática e programação.",
    document: "ata_fundacao_2023.pdf",
    status: "rejeitada",
    submittedAt: "2024-02-25",
    resolvedAt: "2024-03-05",
    rejectionReason: "Documentação incompleta. O CNPJ informado não consta na base da Receita Federal como ativo.",
  },
];
