export const atualizacoesMock = [
  {
    id: 1,
    titulo: "Meta 65% atingida!",
    mensagem: "Graças ao apoio de vocês, já alcançamos 65% da nossa meta. As sessões de fisioterapia seguem acontecendo toda semana. Obrigado pelo carinho!",
    campanha: "Fisioterapia que transforma",
    enviadaEm: "2024-04-15",
  },
];

export const instituicoesPendentesMock = [
  {
    id: 1,
    nome: "Instituto Esperança Viva",
    cnpj: "98.765.432/0001-10",
    cidade: "Campinas",
    estado: "SP",
    email: "contato@esperancaviva.org.br",
    telefone: "+55 19 3333-4444",
    descricao: "Organização focada em apoio a crianças em situação de vulnerabilidade social, oferecendo alimentação, educação complementar e apoio psicológico.",
    documento: "estatuto_social_2024.pdf",
    status: "pendente",
    submetidaEm: "2024-04-18",
  },
  {
    id: 2,
    nome: "Lar Solidário Santana",
    cnpj: "11.222.333/0001-44",
    cidade: "Ribeirão Preto",
    estado: "SP",
    email: "lar@solidariosantana.org.br",
    telefone: "+55 16 3222-5555",
    descricao: "Abrigo para idosos em situação de abandono, com atendimento médico, fisioterapia e atividades de lazer.",
    documento: "registro_cnpj_2024.pdf",
    status: "aprovada",
    submetidaEm: "2024-03-10",
    resolvidaEm: "2024-03-20",
  },
  {
    id: 3,
    nome: "ONG Sonhos em Ação",
    cnpj: "55.666.777/0001-88",
    cidade: "Santos",
    estado: "SP",
    email: "contato@sonhosemacao.org.br",
    telefone: "+55 13 4444-6666",
    descricao: "Projeto de inclusão digital para jovens de comunidades carentes, oferecendo cursos de informática e programação.",
    documento: "ata_fundacao_2023.pdf",
    status: "rejeitada",
    submetidaEm: "2024-02-25",
    resolvidaEm: "2024-03-05",
    motivoRejeicao: "Documentação incompleta. O CNPJ informado não consta na base da Receita Federal como ativo.",
  },
];
